In [77]:
import numpy as np

In [55]:
a = np.array([[[1],
               [2]],
              [[11],
               [12]]])
a.shape

(2, 2, 1)

In [81]:
# 첫 번째 차원 (axis=0)
a[0], a[1]

(array([[1],
        [2]]),
 array([[11],
        [12]]))

In [85]:
# 첫 번째 차원을 기준으로 평균 내기 (axis=0)
a.mean(axis=0)

array([[6.],
       [7.]])

In [83]:
# 두 번째 차원 (axis=1)
a[:, 0], a[:, 1]

(array([[ 1],
        [11]]),
 array([[ 2],
        [12]]))

In [84]:
# 두 번째 차원을 기준으로 평균 내기 (axis=1)
a.mean(axis=1)

array([[ 1.5],
       [11.5]])

In [76]:
# 세 번째 차원 (axis=2)
a[:, :, 0]

array([[ 1,  2],
       [11, 12]])

In [86]:
# 세 번째 차원을 기준으로 평균 내기 (axis=2)
a.mean(axis=2)

array([[ 1.,  2.],
       [11., 12.]])

직관적으로 그려지지 않지만. <br>
첫 번째, 두 번째 차원들을 다 출력해보고. <br>
그 출력된 결과를 가지고 평균 구하는 과정을 생각해보면 좀 낫다.

In [120]:
a = np.array([
    # 첫 번째 이미지
    [[[1, 2], # R
       [3, 4]],
      [[5, 6], # G
       [7, 8]],
      [[9, 10], # B
       [11, 12]]],
    
    # 두 번째 이미지
    [[[13, 14], # R
       [15, 16]],
      [[17, 18], # G
       [19, 20]],
      [[21, 22], # B
       [23, 24]]]
    ])

a.shape

(2, 3, 2, 2)

In [96]:
# 첫 번째 차원 (axis=0)
a[0], a[1]

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12]]]),
 array([[[13, 14],
         [15, 16]],
 
        [[17, 18],
         [19, 20]],
 
        [[21, 22],
         [23, 24]]]))

In [97]:
# 첫 번째 차원을 기준으로 평균 내기 (axis=0)
a.mean(axis=0)

array([[[ 7.,  8.],
        [ 9., 10.]],

       [[11., 12.],
        [13., 14.]],

       [[15., 16.],
        [17., 18.]]])

In [98]:
# 두 번째 차원 (axis=1)
a[:, 0], a[:, 1], a[:, 2]

(array([[[ 1,  2],
         [ 3,  4]],
 
        [[13, 14],
         [15, 16]]]),
 array([[[ 5,  6],
         [ 7,  8]],
 
        [[17, 18],
         [19, 20]]]),
 array([[[ 9, 10],
         [11, 12]],
 
        [[21, 22],
         [23, 24]]]))

In [99]:
# 두 번째 차원을 기준으로 평균 내기 (axis=1)
a.mean(axis=1)

array([[[ 5.,  6.],
        [ 7.,  8.]],

       [[17., 18.],
        [19., 20.]]])

In [100]:
# 세 번째 차원 (axis=2)
a[:, :, 0], a[:, :, 1]

(array([[[ 1,  2],
         [ 5,  6],
         [ 9, 10]],
 
        [[13, 14],
         [17, 18],
         [21, 22]]]),
 array([[[ 3,  4],
         [ 7,  8],
         [11, 12]],
 
        [[15, 16],
         [19, 20],
         [23, 24]]]))

In [101]:
# 세 번째 차원을 기준으로 평균 내기 (axis=2)
a.mean(axis=2)

array([[[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]],

       [[14., 15.],
        [18., 19.],
        [22., 23.]]])

In [102]:
# 네 번째 차원 (axis=3)
a[:, :, :, 0], a[:, :, :, 1]

(array([[[ 1,  3],
         [ 5,  7],
         [ 9, 11]],
 
        [[13, 15],
         [17, 19],
         [21, 23]]]),
 array([[[ 2,  4],
         [ 6,  8],
         [10, 12]],
 
        [[14, 16],
         [18, 20],
         [22, 24]]]))

In [103]:
# 네 번째 차원을 기준으로 평균 내기 (axis=3)
a.mean(axis=3)

array([[[ 1.5,  3.5],
        [ 5.5,  7.5],
        [ 9.5, 11.5]],

       [[13.5, 15.5],
        [17.5, 19.5],
        [21.5, 23.5]]])

In [122]:
# 여러 차원을 함께 고려하여 평균 내기
# 이 부분이 이해 안됨

a.mean(axis=(0,1))

array([[11., 12.],
       [13., 14.]])

In [123]:
a.mean(axis=(0,2,3))

array([ 8.5, 12.5, 16.5])

In [126]:
a.mean(axis=(0,1,2,3))

12.5

In [ ]:
# 일단 지금 받아들이는건..
# axis=(0,2,3)으로 평균을 내면 [R평균, G평균, B평균]으로 나온다는거....